version: '3.8'

services:
  service1:
    build: 
      context: ./Service1
      dockerfile: Dockerfile
    ports:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    deploy:
      replicas: 3

  service2:
    build: 
      context: ./Service2
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Make Docker daemon accessible
    networks:
      - app-network
      
  nginx:
    image: nginx:latest
    ports:
      - "8198:80"  # Only expose Nginx to the outside
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./login.txt:/etc/nginx/login.txt
      - ./nginx/html:/usr/share/nginx/html  # Mount the HTML directory
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
